version: "3"

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - workspace_node_modules:/workspace/node_modules
    command: sleep infinity
volumes:
  workspace_node_modules:
